## create a docker image using gcloud docker
FROM tomcat:jre8
MAINTAINER Soumya Ranjan Suansia (soumya.suansia@gmail.com)
COPY /root/workspace/warstore/cmad-blog.war /usr/local/tomcat/webapps/cmad-blog.war
